config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :photos do 
    resources :comments
  end

  root 'photos#index'
  
  resources :profiles, only: [:show, :edit, :update] do
    resources :photos 
  end

  get 'top-photo', to: 'photos#top', as: 'top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :photo_collections
  has_many :photos, through: :photo_collections
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :photo
  belongs_to :user

  validates :content, length: { minimum: 1 }
  validates :content, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  attr :formatted_date

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :image, :title, :description, presence: true
  validates :user, presence: true

  FEATURED_STATUS = {
    not_featured: 0,
    featured: 1
  }

  def featured?
    self.featured_status == FEATURED_STATUS[:featured]
  end

  def not_featured?
    self.featured_status == FEATURED_STATUS[:not_featured]
  end

  def myPhoto
    ActionController::Base.helpers.image_tag("#{image.url(:thumb)}")
  end
  
  def self.photos_by_comment_count
    Photo.joins(:comments).select("photos.*, count(comments.id) as comment_count").group('photos.id').order("comment_count DESC")
  end

  def self.top_photo
    Photo.photos_by_comment_count.first
  end

  def formatted_date
    self.created_at.strftime("%b %d, %Y")
  end

end

app/models/photo_collection.rb
class PhotoCollection < ApplicationRecord
  belongs_to :collection
  belongs_to :photo
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  has_many :photos, through: :user

  accepts_nested_attributes_for :photos
  
  def username
    self.user.username
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos, dependent: :destroy
  has_one :profile, dependent: :destroy 
  has_many :comments

  after_create :create_profile

  attr :username
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers =>[:facebook]

    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
     end      
    end

  def username
    self.email.gsub(/(@)(.*?)$/, "").capitalize
  end 
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #it raises an "Exception" if there isn't sufficient protection, or if there is a CSFR-type request. 
  #The "Exception" is whatever caused the fault to begin with. This forces Rails to tell you what caused the exception
  before_action :authenticate_user! 

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_photo, only: [:new, :create, :edit, :udpate, :destroy]
  before_action :set_collection, only: [:destroy]
  
  def index
    @collections = current_user.collections
  end

  def new
    @collection = Collection.new
  end

  def create
    @collection = current_user.collections.find_or_initialize_by(name: params[:collection][:name])
    @collection.photos << @photo
    @collection.save

    if @collection.save
      redirect_to collection_path(@collection)
    else
      render 'new'
    end
  end

  def show
    @collection = Collection.find_by(id: params[:id])
  end

  def destroy
    @collection.photos.delete(@photo)
  end

private 
  def set_photo
    if !params[:photo_id].nil?
    @photo = Photo.find_by(id: params[:photo_id])
    end
  end

  def set_collection
    @collection = Collection.find_by(id: params[:id])
  end

end


# i want my user to click a 'collect' button on a photo
# they will be able to choose a drop down of either a new or existing collection
# and the photo will be put into that collection
# the collection will be rendered 

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_photo
  before_action :set_comment, only: [:edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @photo.comments.all, status: 200 }
    end 
  end

  def create
    @comment = @photo.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      render json: @comment, status: 201
    else
      render 'index'
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to photo_comments_path(@photo)
    else 
      render 'edit'
    end
  end
  
  def destroy
    @comment.destroy
    redirect_to photo_path(@photo)
  end

  private
  
    def comment_params
      params.require(:comment).permit(:content)
    end

    def set_photo
      @photo = Photo.find_by(id: params[:photo_id])
    end

    def set_comment
      @comment = @photo.comments.find_by(id: params[:id])
    end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  def index
    if params[:profile_id].nil?
      @photos = Photo.all.order("created_at DESC")
    else
      @profile = Profile.find_by(id: params[:profile_id])
      @photos = @profile.photos.order("created_at DESC")
      render json: @photos
    end 
  end

  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @photo, status: 200 }
    end 
  end

  def new
    @photo = current_user.photos.build
  end

  def create
    @photo = current_user.photos.build(photo_params)
    if @photo.save
      redirect_to @photo, notice: "Your photo was successfully added!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @photo.update(photo_params)
      redirect_to @photo, notice: "Your photo was successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    if current_user.photos.include?(@photo)
      @photo.destroy
      redirect_to root_path, notice: "Your photo was successfully deleted."
    else
      redirect_to @photo, notice: "You do not have permissions to delete this photo."
    end
  end

  def top
    @top_photo = Photo.top_photo
    redirect_to @top_photo
  end

  private

    def photo_params
      params.require(:photo).permit(:title, :description, :image, :featured_status)
    end

    def set_photo
      @photo = Photo.find_by(id: params[:id])
    end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update]

  def show
    # render json: @profile
    @photos = @profile.photos.order('created_at DESC')
  end

  def edit
    @photos = @profile.photos
  end

  def update
    if @profile.update(profile_params)
      redirect_to @profile
    else
      render :edit
    end
  end

  private
  
    def set_profile
      @profile = Profile.find_by(id: params[:id])
    end

    def profile_params
      params.require(:profile).permit(:bio, photos_attributes:[:id, :featured_status])
    end

end 

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user      
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def most_active_user
    @user = User.most_active_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
  def photo_date(photo)
    photo.created_at.strftime("%b %d, %Y")
  end
end

app/views/collections/_form.html.erb
<%= simple_form_for @collection, url: photo_collections_path do |f| %>
  <%= f.input :name, class: 'form-control'%>
  <%= f.button :submit, value: "Collect", class:'btn btn-info'%>
<% end %>

app/views/collections/index.html.erb
<% @collections.each do |collection| %>
  <h1><%= link_to collection.name, collection %></h1>
    <% collection.photos.each do |photo|%>
      <div class="photo">
      <%= link_to photo.myPhoto, photo %>
      </div>
    <% end %>
  <% end %>

app/views/collections/new.html.erb
<div id=photo_show class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">

      <div class= "panel heading photo_image">
        <%= image_tag @photo.image.url %>
      </div>
        <h1> Find or Create New Collection</h1>

      <div class="panel-body"> 
        <%= render 'form' %> 
      </div>
      
    </div>
  </div>
</div>

app/views/collections/show.html.erb
<div class="collection_show">
  <h1 class="page-header"><%= @collection.name %></h1>
  <div class='col-md-12'>
    
    <div id='photos' class="rtl">
      <%= render @collection.photos %>
    </div>
  </div>
</div>

app/views/comments/_comment.html.erb
<p class="comment_user"><strong><%= link_to comment.user.email, profile_path(comment.user.profile) %>: </strong>
  <%= comment.content %></p>

<div class="comment_time">Posted <%= time_ago_in_words(comment.created_at)%> ago

  <% if comment.user == current_user %>
    <%= link_to "Edit", edit_photo_comment_path(comment.photo, comment) %> |
    <%= link_to 'Delete', [comment.photo, comment], method: :delete, data: {confirm: 'Are you sure?'}%>
  <% end %>
</div><br>

app/views/comments/_form.html.erb
<%= simple_form_for ([@photo, @photo.comments.build]) do |f| %>

  <p><%= f.input :content, label: 'Your Comment', :class => 'form-control' %></p><br>
  
  <p class="btn-group">
    <%= f.submit :class => 'btn btn-info'%>
    <%= link_to "Go Back", @photo, :class => 'btn btn-default' %>
  </p>

  <% end %>

app/views/comments/edit.html.erb
<div id="edit_page">
  <div class="row">
    <div class ="col-md-7 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1>Edit Comment </h1>

            <div class="panel-body">
                <%= simple_form_for [@photo, @comment] do |f| %>
                  <% if @comment.errors.any? %>
                    <h2 id="form-group"><%= pluralize(@comment.errors.count, "error") %> prevented your comment from saving</h2>
                    <ul>
                      <% @comment.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                        <% end %>
                    </ul>
                  <% end %>
                  <p><%= f.input :content, label: 'Your Comment', :class => 'form-control' %></p><br>
                  <p class="btn-group">
                    <%= f.submit :class => 'btn btn-info'%>
                    <%= link_to "Go Back", @photo, :class => 'btn btn-default' %>
                  </p>
                <% end %>
            </div>
            
        </div>
      </div>
    </div>
  </div>
</div>

app/views/comments/index.html.erb
<div id=photo_show class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">

      <div class= "panel heading photo_image">
        <%= image_tag @photo.image.url %>
      </div>

      <div class="panel-body">
        <h1><%= @photo.title %></h1>
        <p><%= @photo.description %></p>
        <p class="user">by <%= link_to @photo.user.email, profile_path(@photo.user.profile) %></p>
      </div>

      <div class="panel-footer">
        <div class="row">
         
            <div class="comments">
              <h2><%= @photo.comments.count %> Comments</h2>

                <% @photo.comments.each do |comment| %>
                  <% if !comment.id.nil? %>
                    <%= render comment %>
                  <% else %>
                    <h2 id="form-group"><%= pluralize(comment.errors.count, "error") %> prevented this comment from saving</h2>
                    <ul>
                    <% comment.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                      <% end %>
                    </ul>
                  <% end %>
                <% end %>
          
                <h3>Join Disscussion: </h3>
                <%= render "form" %>
            </div>
         
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inscape</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar navbar-inverse">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to "Inscape", root_path %>
        </div>
          <% if user_signed_in? %>
            <ul class="nav navbar-nav navar-left">
              <li><%= link_to "Profile", profile_path(current_user) %></li>
              <li><%= link_to "Add Photo", new_photo_path %></li>
              <li><%= link_to "Top Photo", top_path %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav navbar-left">
              <li><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></li>
              <li><%= link_to "Join", new_user_registration_path %></li>
              <li><%= link_to "Log In", new_user_session_path %></li> 
            </ul>
          <% end %>
      </div>
    </nav>

    <div class="container">

      <% unless flash.empty? %>
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-info" %>
        <% end %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/photos/_form.html.erb
<%= simple_form_for @photo do |f| %>
  <% if @photo.errors.any? %>
    <h2 id="form-group"><%= pluralize(@photo.errors.count, "error")%> prevented this Photo from saving</h2>
    <ul>
      <% @photo.errors.full_messages.each do | msg | %>
      <li><%= msg %> </li>
      <% end %>
    </ul>
  <% end %>
  <%= f.input :image, as: :file, input_html: { class: 'form-control'} %>
  <%= f.input :title, input_html: { class: 'form-control'} %>
  <%= f.input :description, input_html: { class: 'form-control'} %>
  <%= f.button :submit, class: 'btn btn-info'%>
<% end %>

app/views/photos/_photo.html.erb
<div class="box panel panel-default">
  <%= link_to (image_tag photo.image.url), photo %>
  <h2><%= link_to photo.title, photo %></h2>
  <p><%= time_ago_in_words(photo.created_at)%> ago</p>
  <% if !params[:id].nil? %>
    <%= link_to "Remove from collection", photo_collection_path(photo, @collection), method: :delete, data: { confirm: "Are you sure?"} %>
  <% end %>
</div>

app/views/photos/edit.html.erb
<div id="edit_page">
  <div class="row">
    <div class ="col-md-7 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading">
            <h1> Edit Photo </h1>
            <div class="panel-body"> 
              <%= render 'form' %> 
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/photos/index.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="transitions-enabled masonry photos">
    <% @photos.each do |photo| %>
        <div class="box panel panel-default">
          <%= link_to (image_tag photo.image.url), photo %>
          <h2><%= link_to photo.title, photo %></h2>
          <p><%= time_ago_in_words(photo.created_at)%> ago</p>
        </div>
      <% end %>
  </div>
</div >

app/views/photos/new.html.erb
<div class ="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
          <h1> Post New Photo </h1>
          <div class="panel-body"> 
            <%= render 'form' %> 
          </div>
      </div>
    </div>
  </div>
</div>

app/views/photos/show.html.erb
<div id=photo_show class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">

      <div class="panel heading photo_image">
        <%= image_tag @photo.image.url, :class => "photoImage" %>
      </div>

      <div class="panel-body">
        <h1 class="photoTitle"><%= @photo.title %></h1>
        <p class="photoDescription"><%= @photo.description %></p>
        <p class="photoDate">Created <%= photo_date(@photo) %></p>
      </div>

      <div class="panel-footer">
        <div class="row">

          <div class="col-md-6">
            <p>by <%= link_to @photo.user.email, profile_path(@photo.user.profile), :class => "photoUserEmail" %></p>
            <p><%= link_to "#{@photo.comments.count} Comments", photo_comments_path(@photo), :class => "photoComments", :"data-id" => "#{@photo.id}"  %></p>
          </div><br>

          <div class="js-show-comments comments"></div>

          <%= form_for ([@photo, @photo.comments.build]) do |f| %>
            <p><%= f.text_area :content, :class => "form-control" %></p><br>
            <%= f.submit :class => "btn-warning btn" %>
          <% end %><br>

          <div class="col-md-6">
            <div class="btn-group pull-right">
              <% if user_signed_in? && current_user.photos.include?(@photo) %>
                <%= link_to "Edit", edit_photo_path, class: "btn btn-info" %>
                <%= link_to "Delete", photo_path, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger" %>
              <% end %>
            </div>
          </div>

        </div>
      </div>

    </div>
  </div>
</div>


<button type="button" class="btn btn-warning"><a href="#" class="js-previous jsb" data-id="<%=@photo.id%>">Previous</a></button>
<button type="button" class="btn btn-warning pull-right"><a href="#" class="js-next jsb" data-id="<%=@photo.id%>">Next</a></button>

app/views/profiles/_form.html.erb
<%= simple_form_for @profile do |f| %>

  <% if @profile.errors.any? %>
    <h2 id="form-group"><%= pluralize(@profile.errors.count, "error") %> prevented this Photo from saving</h2>
    <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
  <% end %>

  <%= f.input :bio, input_html: {class: 'form-control'} %>

  <section class="main">
    <label>Featured Profile Photos</label>
      <%= f.simple_fields_for :photos do | ff |%>
       <%= ff.check_box :featured_status %>
        <label><%= ff.object.myPhoto %></label>
      <% end %>
  </section>
  
  <%= f.button :submit, value: "Update Bio", class: 'btn btn-info'%>
<% end %>

app/views/profiles/edit.html.erb
<div class ="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
          <h1> Update Your Profile </h1>
          <div class="panel-body"> 
            <%= render 'form' %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="page-header">
  <h3><%= @profile.user.username %><br>    

    <% if current_user.profile == @profile %>
        <button type="button" class="btn btn-secondary btn-xs"><%= link_to "Edit Bio", edit_profile_path %></button>
    <% end %>

      <button type="button" class="btn btn-secondary btn-xs js-get-photos" data-id="<%=@profile.id%>">All Photos</button><br>
      <small class="bio-text"><%= @profile.bio %></small><br>

  </h3>
</div>

<div class="photos-sorted-by-comment photos"></div>

<div class="col-md-12">
  <div class="rtl transitions-enabled photos">

    <div id="all-photos-div"></div>

    <div id='featured-photos'>
      <h5>Featured Photos</h5>
      <% @photos.each do |photo| %>
        <% if photo.featured? %>
          <div class="box panel panel-default">
            <%= link_to (image_tag photo.image.url), profile_photo_path(photo.user.profile.id, photo) %>
            <h2><%= link_to photo.title, photo %></h2>
            <p><%= photo_date(photo) %></p>
          </div>
        <% end %>
      <% end %>
    </div>

  </div>
</div>

app/views/users/most_active_user.html.erb
<%= @user.email %>
<%= @user.photos.count %>